import os

# Cache location
DEFAULT_XDG_CACHE_HOME = "~/.cache"
XDG_CACHE_HOME = os.getenv("XDG_CACHE_HOME", DEFAULT_XDG_CACHE_HOME)
DEFAULT_BALAUR_CACHE_HOME = os.path.join(XDG_CACHE_HOME, "balaur")
BALAUR_CACHE_HOME = os.path.expanduser(os.getenv("BALAUR_CACHE", DEFAULT_BALAUR_CACHE_HOME))

DEFAULT_BALAUR_DATA_CACHE = os.path.join(BALAUR_CACHE_HOME, "data")
BALAUR_DATA_CACHE = os.getenv("BALAUR_DATA_CACHE", DEFAULT_BALAUR_DATA_CACHE)

DEFAULT_BALAUR_RUN_CACHE = os.path.join(BALAUR_CACHE_HOME, "runs")
BALAUR_RUN_CACHE = os.getenv("BALAUR_RUN_CACHE", DEFAULT_BALAUR_RUN_CACHE)